# Generated by Django 3.0.3 on 2020-02-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('nick_name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=256)),
                ('mobile_no', models.CharField(max_length=14, null=True)),
                ('location', models.CharField(max_length=10)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
    ]
