# Generated by Django 3.0.3 on 2020-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_no',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
