# Generated by Django 3.0.3 on 2020-02-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200219_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.TimeField(null=True),
        ),
    ]
