# Generated by Django 3.1.7 on 2021-06-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mess',
            table='mess',
        ),
    ]
