# Generated by Django 3.1.7 on 2022-03-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0005_auto_20211212_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
