# Generated by Django 4.1 on 2022-08-25 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess_app', '0006_auto_20220324_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messeventevent',
            name='mess',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mess_id_on_mess_event', to='mess_app.mess'),
        ),
        migrations.AlterField(
            model_name='messnuserevent',
            name='mess',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mess_id_on_mess_n_user', to='mess_app.mess'),
        ),
        migrations.AlterField(
            model_name='messnuserevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
